services:
  mini-org-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-org-viewer-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped